os: linux

dist: xenial

language: php

php:
    - 7.2

branches:
    only:
        - main

jobs:
    include:
        - stage: Tests
          before_script:
            - phpenv config-rm xdebug.ini
            - composer self-update
            - composer install
            - touch database/database.sqlite
            - cp .env.travis .env
            - php artisan key:generate
            - php artisan migrate --force
            - php artisan passport:install
          script: php artisan Test
        - stage: Deploy
          script: skip
          deploy:
            deploy:
              skip_cleanup: true
              provider: heroku
              strategy: api
              api_key:
                secure: "kWs/4d8BIPLz3/u7Xe/dK6kY0tJiroq5ilyyc4KpwD2QVJHcGwNOOY/YIuujPTZ2DR0fM0589hin59wEdse1xJeVeAd0s1dfTWmh7lohxvTUf92z8CJLo+EzEJZFLBWYEvT0xI2L7nnQJmva9EI57hbzpQEGwgPQVKjuELpOHX2cq/h/3N/pvPnzIlvuVyU8CwYAAMm6CbnC2XbBBkF+lOMOzO2xl+V6Ce5JN9d2OX2BfGInDiTu1ko57lZwxX7e95tWRy5gPK1ftjmh8TV2OHqXVb6rRGaOXxD7dR55aZYe7G+KzKmmoxv1k9JKDRS5S8Qho7klQqT4TinOfnVPo2EsH9Uz497eQPwQN91OogZgjdXg71b8U4QzgYk46xGiVa2QzppzlxlcGTaLCEH9IDdpUoqdDVhzfmIWpKRCoEeReo7rYfPyrbB4jqpFpxdI4VbQgvqhaQWkgOJpHTbOV3v8/uS9keD33LXtullVSXl9auClAixKfd8lEVxumwbWOk/oCfiiI27lyxdpkH2koyButwLeQy0Zzr2ecrK5E9Uh1Th6Vx26nq7pVuWi7EfAjeTbAPe0W0bT4d4Mob0wPbyO/+W6edqdQN+A9AKom33iXxTEKPrvRnekE2Ar5ZdCdu56YAsC0xqOdD35c83HUe2nDNT8EwS5yppEUDQ/X2I="
              app: titrack
              on: main